//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditCategory
    {
        public int CategoryID { get; set; }
        public string OldCategoryName { get; set; }
        public string OldDescription { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
